name:                elm-architecture
version:             0.1.0.0
github:              "ohri-anurag/elm-architecture"
license:             BSD3
author:              "Anurag Ohri"
maintainer:          "anuragohri92@gmail.com"
copyright:           "2020 Anurag Ohri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>

dependencies:
- base >= 4.7 && < 5
- colour
- lens
- safe
- sdl2
- StateVar
- text

library:
  source-dirs: src

executables:
  elm-architecture:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-architecture

tests:
  elm-architecture-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-architecture
